[package]
name = "leta"
version = "0.1.0"
edition = "2021"

[dependencies]
let_result = { version = "0.1.0", path = "../let_result" }
let_object_emitter = { version = "0.1.0", path = "../let_object_emitter" }
let_assembler = { version = "0.1.0", path = "../let_assembler" }
