[package]
name = "letl"
version = "0.1.0"
edition = "2021"

[dependencies]
let_result = { version = "0.1.0", path = "../let_result" }
let_resolver = { version = "0.1.0", path = "../let_resolver" }
let_opcodes = { version = "0.1.0", path = "../let_opcodes" }
